### PR TITLE
Addtests

### LINKED ISSUE #7: add a testing suite
As an engineer I need to write tests to work in a test driven way and accommodate future extension and use of modules.

### PR DESCRIPTION
**Pull request by riftrid3r**
this closes #7 .

### CODE REVIEW

**Comment by riftrid3r** [comment]
Yes, you are right about the .gitignore. I'm not sure about chai. It was auto generated from ```npm install chai --save```. I'll look into it further.

**Comment by jonathandavidlewis** [comment]
Try --save-dev

**Comment by riftrid3r** [comment]
Sick. Thanks. :+1:

**Comment by riftrid3r** [comment]
@jonathandavidlewis, updated .gitignore to exclude all from node_modules/, because who wants to see all that junk in a repo? no one that's who! ha! Next I updated package.json to mv dev deps to the dev deps object. Thanks for your help! Let me know if you catch anything else. If not I am comfortable with a squash and merge here.

**Pull request merged**
