### PR TITLE
Addtests

### PR DESCRIPTION
**Pull request by riftrid3r**
Add a basic assertion to test for the existence of '.add' method so we can be sure tests are working.

### CODE REVIEW

**Comment by riftrid3r** [comment]
@jonathandavidlewis, This PR is updated to address issues you mentioned.

**Comment by riftrid3r** [comment]
@jonathandavidlewis, actually adding var to line 1 breaks test suite completely. Likely something to do with exporting the object and the scope it exists in. Will look into this for a later fix.

**Comment by jonathandavidlewis** [comment]
That’s not a good sign.  :/

On Jul 31, 2017, at 4:03 PM, Drew Billings <notifications@github.com> wrote:

@jonathandavidlewis <https://github.com/jonathandavidlewis>, actually
adding var to line 1 breaks test suite completely. Likely something to do
with exporting the object and the scope it exists in. Will look into this
for a later fix.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/riftrid3r/js-linked-list/pull/11#issuecomment-319221008>,
or mute the thread

**Comment by jonathandavidlewis** [comment]
Good you refactored that part.  I was actually writing that as a
suggestion. :)

**Comment by riftrid3r** [comment]
Do you have any idea why the test might be breaking when we add the var keyword to the beginning of the object def?

**Comment by jonathandavidlewis** [comment]
What's the error?

Is List already declared before that point?

**Comment by riftrid3r** [comment]
/home/dib/Source/jslinkedlist/test/test.js:7
        var list = new List();
                       ^
ReferenceError: List is not defined

**Comment by riftrid3r** [comment]
Alright I figured it out. We are polluting the global space by not
constricting the scope in our declaration which is exactly what keyword
"var" does in JS. So we do need to export the function. I think we use:
```
exports.List = function(){
...code...
}
```

**Comment by riftrid3r** [comment]
I Think I will merge this for now and fix the namespace issue later.

**Pull request merged**
